# ============================================================================
# Continuous Deployment Pipeline
# 1. Espera a que Pytest (workflow separado) pase correctamente.
# 2. Si el commit fue en main, publica la imagen en Docker Hub.
# 3. Después de publicar, ejecuta el despliegue en Render vía webhook.
# ============================================================================

name: CD Pipeline

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  publish_and_deploy:
    name: Publish Docker Image & Deploy (Main)
    name: Publish Docker Image & Deploy (Main)
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USER }}/uvlhub
          TAG=main-$(date +'%Y%m%d-%H%M%S')
          TAG=main-$(date +'%Y%m%d-%H%M%S')

          echo "Building image with tag: $TAG"

          docker build -t $IMAGE:$TAG -f docker/images/Dockerfile.prod .
          docker push $IMAGE:$TAG

          docker tag $IMAGE:$TAG $IMAGE:latest
          docker push $IMAGE:latest

      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
