name: CD Pipeline PreDeploy

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: ["trunk"]         # Only react to CI runs on trunk

jobs:
  publish_and_deploy:
    name: Publish Docker Image & Deploy (Trunk)
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Gate on CI success

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USER }}/uvlhub
          TAG=trunk-$(date +'%Y%m%d-%H%M%S')

          echo "Building image with tag: $TAG"

          docker build -t $IMAGE:$TAG -f docker/images/Dockerfile.prod .
          docker push $IMAGE:$TAG

          docker tag $IMAGE:$TAG $IMAGE:latest-trunk
          docker push $IMAGE:latest-trunk

      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_PREDEPLOY_HOOK_URL }}
